apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-env
spec:
  params:
    - name: node-version
      value: $(params.node-version)
    - name: npm-version
      value: $(params.npm-version)
    - name: prerelease
      value: $(params.prerelease)   
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: execute
      image: node:$(params.node-version)
      script: |
        #!/bin/bash
        ARTIFACTS_PATH="$(workspaces.output.path)"
        cd $ARTIFACTS_PATH

        if [ "$(params.prerelease)" == "true" ]; then
          source bin/install-prerelease.sh 
        fi

        if [ -n "$(params.npm-version)" ]; then
          npm install npm@$(params.npm-version) -g
        fi

        echo "Using node: $(node --version)"
        echo "Using npm: $(npm --version)"

        if command -v arch >/dev/null 2>&1; then
          echo "Architecture: $(arch)"
        elif command -v uname >/dev/null 2>&1; then
          echo "Architecture: $(uname -m)"
        else
          echo "Architecture information not available"
        fi
