name: scheduled-test-stats

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 06:00 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Execute stats
        run: |
          stats_cases=$(node bin/gather-test-stats.js)
          echo $stats_cases
          echo "instana_stats_test_cases=$stats_cases" >> $GITHUB_ENV

      - name: Print env from previous step
        run: |
          echo "From .env"
          echo "${{ env.instana_stats_test_cases }}"
          echo "From $"
          echo $instana_stats_test_cases
