name: scheduled-test-stats

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 06:00 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Execute stats
      run: node bin/gather-test-stats.js
